
server:
  port: 8761 # 8762 # 8763
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: true   # 注册自己的功能，集群的时候必须开启
    fetch-registry: true  # 获取服务列表的功能,集群的时候必须开启

    
